[theme]
primaryColor = "#8C352D"
backgroundColor = "#FCFAF7"
secondaryBackgroundColor = "#F3EEE7"
textColor = "#2D2926"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
